version: '3'
services:
  app:
    image: ubuntu:latest
    container_name: my_ubuntu_container
    volumes:
      - ./app:/app  # Monta el directorio app de tu máquina real al contenedor
    build:
      context: .
      dockerfile: Dockerfile  # Usará un archivo Dockerfile para instalar los requerimientos
    stdin_open: true  # Mantiene la terminal abierta
    tty: true  # Habilita el modo interactivo
    command: bash -c "bash"  # Inicia un terminal bash al ejecutar el contenedor
